version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    directories:
      - "."
    groups:
      production-major:
        dependency-type: production
        update-types:
          - major
      production-minor:
        dependency-type: production
        update-types:
          - minor
          - patch
      development:
        dependency-type: development
