#!/usr/bin/env sh

if [ -z ${1+x} ]; then
  echo 'Please provide an commit message'
  exit 1
fi

hugo -d _public --minify
git switch public

branch=$(git rev-parse --abbrev-ref HEAD)
if [ $branch != 'public' ];
then
  echo 'Unable to checkout public'
  exit 1
fi

cp -r _public/* .

git add --all
git commit -m "$1"
git push

git switch main
